export enum Icon {
    WARNING = "⚠",
    THUMBS_UP = "👍",
    THUMBS_DOWN = "👎",
    CELEBRATE = "🎉",
    MESSAGE = "✉",
    CLOSE = "X",
    HELP = "i",
    WINNER = "👑",
    ONE = "⚀",
    TWO = "⚁",
    THREE = "⚂",
    FOUR = "⚃",
    FIVE = "⚄",
    SIX = "⚅",
}