export enum Icon {
    WARNING = "⚠",
    THUMBS_UP = "👍",
    THUMBS_DOWN = "👎",
    CELEBRATE = "🎉",
    MESSAGE = "✉",
    CLOSE = "X",
    HELP = "i",
    KING_PIECE = "👑",
    ALL_PIECE = "✷",
    HORIZONTAL_PIECE = "⇆",
    VERTICAL_PIECE = "⇵",
    DIAGONAL_PIECE = "╳",
    ONE = "⚀",
    TWO = "⚁",
    THREE = "⚂",
    FOUR = "⚃",
    FIVE = "⚄",
    SIX = "⚅",
}