export enum MenuTag {
  BOARD_GAME = "BOARD_GAME",
  ONE_A_DAY = "ONE_A_DAY",
  TWO_PLAYER = "TWO_PLAYER",
  ONE_PLAYER = "ONE_PLAYER",
  WORD = "WORD",
  GAMBLING = "GAMBLING",
  TRIVIA = "TRIVIA",
  MULTI_PLAYER = "MULTIPLAYER",
}
